### ISSUE TITLE
환경별 Elasticsearch 클러스터 구성

### ISSUE THREAD

**Issue by rkaehdaos** [rkaehdaos/Get-your-hands-dirty-on-clean-architecture#16]
구조화된 로깅 + Logstash + Elasticsearch 구성에서 환경별 Elasticsearch 운영 형태와 사이즈를 정리해드리겠습니다.

### **개발 환경 (Development)**

**클러스터 구성**
- **단일 노드** 또는 **2노드 클러스터**
- 복제본(replica) 없음 또는 1개
- 마스터 노드와 데이터 노드 겸용

**사이즈 권장사항**[1]
- **메모리**: 노드당 8GB RAM (힙 4GB)
- **디스크**: 100-500GB (개발 데이터 기준)
- **CPU**: 2-4 코어
- **데이터 보존**: 7-30일

**설정 예시**
```yaml
cluster.name: logging-dev
node.name: dev-node-1
discovery.type: single-node
xpack.security.enabled: false
```

### **스테이징 환경 (Staging)**

**클러스터 구성**
- **3노드 클러스터** (최소 고가용성 구성)
- 1개 복제본 설정
- 전용 마스터 노드 권장하지 않음 (리소스 절약)

**사이즈 권장사항**[2]
- **메모리**: 노드당 16-32GB RAM (힙 8-16GB)
- **디스크**: 1-2TB per node
- **CPU**: 4-8 코어
- **데이터 보존**: 30-90일

**클러스터 설정**
```yaml
cluster.name: logging-stage
node.roles: [master, data]
discovery.seed_hosts: ["stage-es-1", "stage-es-2", "stage-es-3"]
cluster.initial_master_nodes: ["stage-es-1", "stage-es-2", "stage-es-3"]
```

### **운영 환경 (Production)**

**클러스터 구성**[3][2]
- **최소 5노드**: 3개 전용 마스터 노드 + 2개 이상 데이터 노드
- **고가용성**: 3개 가용 영역에 분산 배치
- **Hot-Warm-Cold 아키텍처** 적용

**사이즈 권장사항**

**마스터 노드**
- **메모리**: 4-8GB RAM
- **디스크**: 50-100GB (SSD)
- **CPU**: 2-4 코어

**데이터 노드 (Hot)**[1]
- **메모리**: 64GB RAM (힙 30GB)
- **디스크**: 2-10TB (SSD)
- **CPU**: 16-32 코어
- **메모리:데이터 비율**: 1:30

**데이터 노드 (Warm/Cold)**
- **메모리**: 32-64GB RAM
- **디스크**: 10-50TB (HDD 가능)
- **CPU**: 8-16 코어
- **메모리:데이터 비율**: 1:160

### **중소규모 운영환경**[1]

**요구사항**
- 일일 로그 데이터: 10GB
- 보존 기간: 90일 (Hot 30일, Warm 60일)
- 복제본: 1개

**계산 과정**
```
총 데이터 = 10GB × 90일 × 2(복제본) = 1,800GB
여유분 포함 = 1,800GB × 1.25 = 2,250GB
필요 노드 수 = 2,250GB ÷ (64GB RAM × 30 비율) = 2개 노드
```

**최종 구성**
- 마스터 노드: 3개 (4GB RAM, 2 CPU)
- 데이터 노드: 3개 (64GB RAM, 16 CPU, 2TB SSD)

### **대규모 운영환경**[1]

**요구사항**
- 일일 로그 데이터: 100GB
- 보존 기간: 365일 (Hot 30일, Warm 90일, Cold 245일)
- 복제본: 1개

**계산 과정**
```
Hot 데이터 = 100GB × 30일 × 2 = 6,000GB
Warm 데이터 = 100GB × 90일 × 2 = 18,000GB
Cold 데이터 = 100GB × 245일 × 2 = 49,000GB
총 데이터 = 73,000GB (약 73TB)
```

**최종 구성**
- 마스터 노드: 3개 (8GB RAM, 4 CPU)
- Hot 데이터 노드: 4개 (64GB RAM, 32 CPU, 2TB SSD)
- Warm 데이터 노드: 6개 (32GB RAM, 16 CPU, 4TB SSD)
- Cold 데이터 노드: 8개 (16GB RAM, 8 CPU, 8TB HDD)

### **클러스터 명명 규칙**[4]
```yaml
# 개발환경
cluster.name: logging-dev

# 스테이징환경  
cluster.name: logging-stage

# 운영환경
cluster.name: logging-prod
```

### **보안 설정**
```yaml
# 개발환경 (보안 비활성화)
xpack.security.enabled: false

# 스테이징/운영환경 (보안 활성화)
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
```

### **인덱스 생명주기 관리 (ILM)**
```json
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_age": "1d",
            "max_size": "50GB"
          }
        }
      },
      "warm": {
        "min_age": "30d"
      },
      "cold": {
        "min_age": "90d"
      },
      "delete": {
        "min_age": "365d"
      }
    }
  }
}
```

## 성능 최적화 권장사항

**인덱싱 성능**[1]
- **벌크 사이즈**: 12k 문서 (약 13.7MB)
- **클라이언트 수**: 16개 (62K events/sec 달성 가능)
- **샤드 크기**: 20-40GB per shard

**검색 성능**
- **복제본**: 검색 부하 분산을 위해 최소 1개
- **캐싱**: 필드 데이터 캐싱 활용
- **인덱스 패턴**: 시간 기반 인덱스 분할

이러한 구성을 통해 각 환경의 특성에 맞는 효율적인 Elasticsearch 클러스터를 운영할 수 있습니다[5][6][7].

출처
[1] Benchmarking and sizing your Elasticsearch cluster for ... https://www.elastic.co/blog/benchmarking-and-sizing-your-elasticsearch-cluster-for-logs-and-metrics
[2] Elasticsearch cluster planning/sizing - Elastic Discuss https://discuss.elastic.co/t/elasticsearch-cluster-planning-sizing/330579
[3] Run Elasticsearch in production | Elastic Docs https://www.elastic.co/docs/deploy-manage/production-guidance/elasticsearch-in-production-environments
[4] EXTRA: Elasticsearch Configuration Checklist · GitBook https://madhuakula.com/content/ninja-level-infrastructure-monitoring/elasticsearch-config-checklist.html
[5] 프로그래밍 programming.logging
[6] 프로그래밍 programming.cross_cutting_concerns
[7] 프로그래밍 programming.spring_framework
[8] Elasticsearch cold log cluster sizing - Reddit https://www.reddit.com/r/elasticsearch/comments/1435p6d/elasticsearch_cold_log_cluster_sizing/
[9] Elasticsearch: Concepts, Deployment Options and Best ... https://www.netapp.com/learn/cvo-blg-elasticsearch-concepts-deployment-options-and-best-practices/
[10] Elasticsearch on Kubernetes: Deploy & Scale Easily https://portworx.com/elasticsearch-kubernetes/
[11] Elasticsearch: From development to production in 15 minutes https://www.slideshare.net/slideshow/elasticsearch-from-development-to-production-in-15-minutes/239045957
[12] The Complete Guide to the ELK Stack https://logz.io/learn/complete-guide-elk-stack/
[13] ElasticSearch behaves different in production environment https://stackoverflow.com/questions/40661632/elasticsearch-behaves-different-in-production-environment
